### PR TITLE
Adding Brainrender | ushape3D | Vampire | Suite2p

### PR DESCRIPTION
**Pull request by LSeu-Open**
Brainrender is a very convenient way to do visualization of three dimensional neuro-anatomical data.  Using this for a long time, i recommend it.

### CODE REVIEW

**Comment by LSeu-Open** [comment]
Adding u-shape a Very cool tools for morphological motifs detection on cells

**Comment by LSeu-Open** [comment]
Adding VAMPIRE analysis tool. Amazing tool for quantifies and visualizes heterogeneity of cell and nucleus morphology

**Comment by LSeu-Open** [comment]
Adding Suite2p a nice Pipeline for processing two-photon calcium imaging data. including (Registration, Cell detection, Spike detection and  a Visualization GUI)

**Comment by hallvaaw** [comment]
Thanks @LSeu-994.

**Pull request merged**
